/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed-variant': '#665f00',
        'on-tertiary-fixed': '#484200',
        'on-tertiary-container': '#5b5500',
        'on-primary-container': '#375500',
        'inverse-surface': '#fcf8f8',
        'on-secondary': '#001e4b',
        'primary-fixed': '#b1ff24',
        'primary-dim': '#a4f005',
        'on-primary': '#3e5e00',
        secondary: '#6a9cff',
        'on-secondary-fixed-variant': '#004caa',
        background: '#0e0e0e',
        'surface-container-low': '#131313',
        tertiary: '#fff6ab',
        'on-primary-fixed-variant': '#466900',
        'on-background': '#ffffff',
        'outline-variant': '#494847',
        'error-dim': '#d53d18',
        'tertiary-fixed': '#f7e953',
        'on-primary-fixed': '#304a00',
        'tertiary-fixed-dim': '#e8da46',
        'on-tertiary': '#645d00',
        'primary-fixed-dim': '#a4f005',
        'on-error-container': '#ffd2c8',
        'surface-variant': '#262626',
        'on-secondary-fixed': '#003173',
        'surface-container-highest': '#262626',
        'primary-container': '#a4f005',
        'tertiary-dim': '#e8da46',
        'on-surface-variant': '#adaaaa',
        surface: '#0e0e0e',
        'secondary-container': '#0059c5',
        'on-secondary-container': '#f7f7ff',
        'error-container': '#b92902',
        'on-surface': '#ffffff',
        outline: '#777575',
        error: '#ff7351',
        'inverse-on-surface': '#565554',
        'surface-container-lowest': '#000000',
        'secondary-fixed': '#bfd1ff',
        'inverse-primary': '#456900',
        'secondary-dim': '#006ff0',
        'on-error': '#450900',
        'secondary-fixed-dim': '#aac3ff',
        primary: '#b1ff24',
        'surface-tint': '#b1ff24',
        'tertiary-container': '#f7e953',
        'surface-bright': '#2c2c2c',
        'surface-container': '#1a1919',
        'surface-dim': '#0e0e0e',
        'surface-container-high': '#201f1f',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
